# Prompt Recorder - Windows Auto-start Setup Script
# Usage: Run this script as Administrator

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Prompt Recorder - Auto-start Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check administrator privileges
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "Error: Please run this script as Administrator!" -ForegroundColor Red
    Write-Host "Right-click PowerShell and select 'Run as Administrator'" -ForegroundColor Yellow
    pause
    exit 1
}

# Get project path
$projectPath = $PSScriptRoot
$backendPath = Join-Path $projectPath "backend"

# Check if path exists
if (-not (Test-Path $backendPath)) {
    Write-Host "Error: Cannot find backend directory: $backendPath" -ForegroundColor Red
    pause
    exit 1
}

# Check package.json
$packageJson = Join-Path $backendPath "package.json"
if (-not (Test-Path $packageJson)) {
    Write-Host "Error: Cannot find package.json: $packageJson" -ForegroundColor Red
    pause
    exit 1
}

# Get Node.js path
$nodePath = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $nodePath) {
    Write-Host "Error: Cannot find Node.js, please install Node.js first" -ForegroundColor Red
    pause
    exit 1
}

Write-Host "Project path: $projectPath" -ForegroundColor Green
Write-Host "Backend path: $backendPath" -ForegroundColor Green
Write-Host "Node.js path: $nodePath" -ForegroundColor Green
Write-Host ""

# Create startup script
$startScript = Join-Path $projectPath "start-backend.ps1"
$startScriptContent = @"
# Prompt Recorder Backend - Startup Script
# This script is auto-generated by setup-autostart.ps1

`$ErrorActionPreference = "Stop"

# Set working directory
`$backendPath = "$backendPath"
Set-Location `$backendPath

# Check if dist directory exists, if not, build
if (-not (Test-Path "dist\server.js")) {
    Write-Host "Building backend code..." -ForegroundColor Yellow
    & npm run build
    if (`$LASTEXITCODE -ne 0) {
        Write-Host "Build failed!" -ForegroundColor Red
        exit 1
    }
}

# Start backend service
Write-Host "Starting Prompt Recorder backend service..." -ForegroundColor Cyan
Start-Process -FilePath "$nodePath" -ArgumentList "dist/server.js" -WorkingDirectory `$backendPath -WindowStyle Hidden

Write-Host "Prompt Recorder backend service started" -ForegroundColor Green
"@

Write-Host "Creating startup script..." -ForegroundColor Yellow
$startScriptContent | Out-File -FilePath $startScript -Encoding UTF8 -NoNewline
Write-Host "Startup script created: $startScript" -ForegroundColor Green

# Create VBS script (for hidden window)
$vbsScript = Join-Path $projectPath "start-backend-hidden.vbs"
$vbsContent = @"
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run "powershell.exe -ExecutionPolicy Bypass -File ""$startScript""", 0, False
Set WshShell = Nothing
"@

Write-Host "Creating VBS hidden window script..." -ForegroundColor Yellow
$vbsContent | Out-File -FilePath $vbsScript -Encoding ASCII
Write-Host "VBS script created: $vbsScript" -ForegroundColor Green

# Check for existing task in Task Scheduler
$taskName = "PromptRecorderBackend"
$existingTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue

if ($existingTask) {
    Write-Host "Found existing task, will delete and recreate..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
}

# Create scheduled task
Write-Host "Creating Windows scheduled task..." -ForegroundColor Yellow

$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsScript`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERNAME" -LogonType Interactive -RunLevel Highest
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

try {
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "Prompt Recorder Backend Service - Auto-start on login" | Out-Null
    Write-Host "Scheduled task created: $taskName" -ForegroundColor Green
} catch {
    Write-Host "Error: Failed to create scheduled task: $_" -ForegroundColor Red
    pause
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup completed!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Tips:" -ForegroundColor Yellow
Write-Host "1. Backend service will auto-start on next login" -ForegroundColor White
Write-Host "2. To test immediately, run: .\start-backend.ps1" -ForegroundColor White
Write-Host "3. To setup frontend auto-start, run: .\setup-autostart-frontend.ps1" -ForegroundColor White
Write-Host "4. To disable auto-start, run: Unregister-ScheduledTask -TaskName '$taskName' -Confirm:`$false" -ForegroundColor White
Write-Host "5. To check task status, run: Get-ScheduledTask -TaskName '$taskName'" -ForegroundColor White
Write-Host ""

pause
