# Prompt Recorder Backend - Startup Script
# This script is auto-generated by setup-autostart.ps1

$ErrorActionPreference = "Stop"

# Set working directory
$backendPath = "D:\garage\-prompt_recorder\-prompt_recorder\backend"
Set-Location $backendPath

# Check if dist directory exists, if not, build
if (-not (Test-Path "dist\server.js")) {
    Write-Host "Building backend code..." -ForegroundColor Yellow
    & npm run build
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Build failed!" -ForegroundColor Red
        exit 1
    }
}

# Start backend service
Write-Host "Starting Prompt Recorder backend service..." -ForegroundColor Cyan
Start-Process -FilePath "C:\Program Files\nodejs\node.exe" -ArgumentList "dist/server.js" -WorkingDirectory $backendPath -WindowStyle Hidden

Write-Host "Prompt Recorder backend service started" -ForegroundColor Green